### ISSUE TITLE
gem

### ISSUE THREAD

**Issue by ly123525** [microwisesystem/blacksand#2]
Git error: command `git clone 'git@gitlab.com/microwise/blacksand.git' "/Users/admin/.rvm/gems/ruby-2.3.0/cache/bundler/git/blacksand-b2bc847218e0439820be9c98aa4429b3b442b504" --bare --no-hardlinks --quiet`

**Comment by bastengao** [comment]
@ly123525 我刚才发布了 gem, 你可以直接使用 `gem 'blacksand'`

**Comment by bastengao** [comment]
#1  @ly123525 咱们在这里讨论吧。

Gemfile 头部添加这行试试
```
source "https://rails-assets.org"
```

**Comment by bastengao** [comment]
@ly123525 我完善了文档，添加了示例说明，目前只支持 rails 5.1 一下的版本
